name = "Metalhead"
uuid = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
version = "0.6.1"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
BSON = "0.3.2"
Flux = "0.12"
Functors = "0.2"
julia = "1.4"
NNlib = "0.7.34"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[publish]
title = "Metalhead.jl"

[targets]
test = ["Test"]
